site_name: gaigar
site_url: "https://xin-huang.github.io/gaigar"
repo_url: "https://github.com/xin-huang/gaigar"
edit_uri: ""
docs_dir: 'docs'
theme:
  name: material
  palette:
    primary: teal
    accent: indigo
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - gaigar
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - codehilite
extra_javascript:
  - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
nav:
- Home: 'index.md'
- User Guide:
  - Logistic Regression: 'userguide/lr.md'
  - U-Net: 'userguide/unet.md'
  - Performance: 'userguide/eval.md'
